# Site settings
author: Ghost Script
title: The Ghost Of Coding Future.
header-img: img/home-bg.png
email: tariqbailey627@gmail.com
copyright_name: Ghost Script
description: > # this means to ignore newlines until "baseurl:"
  A friendly ghost.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  GhostScript40

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
